### ISSUE TITLE
Enter to the game (create the game)

### ISSUE THREAD

**Issue by Kassaila** [hakobyant/blot#65]
After running the project and filling all the fields to create the game, nothing happens.
What can be wrong?
Please, help
https://prnt.sc/ru1npr

**Comment by Albertmt** [comment]
Are there any errors in the logs?

**Comment by Kassaila** [comment]
Hello.
In browser console: https://prnt.sc/ruly6r
In terminal no errors. But not running nodemon, I don't install it globally.

**Comment by hakobyant** [comment]
Hi Kassaila, I think these errors suggest that the server is not running. Is it possible you are only running the client and not the server, i.e. in terminal running `npm run client`?
We usually run the client and the server together by running `npm run dev`. So further info on how you run the code might be helpful in figuring out what's going wrong. Thanks in advance!

**Comment by hakobyant** [comment]
This pull request should solve the issue. We did not have the `nodemon` package in the requirements thus this did not allow to run the server application.

**Comment by hakobyant** [comment]
Could you double check if the issue is fixed on your end, @Kassaila ? Thanks!

**Comment by Kassaila** [comment]
Thanks for the fix. I have run the project and create the game.
